/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import javax.swing.JOptionPane;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author ESTUDIANTE
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public static ArrayList<Corredor> corredores;

    String URL;
    int indice;
    public Registro() {
        corredores = new ArrayList<>();
        initComponents();
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * waRNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbg_tipoEstudiante = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_verContraseña = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        lbl_mensajes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        Imagen = new javax.swing.JLabel();
        SelImagen = new javax.swing.JButton();

        setTitle("Registro");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nuevo Usuario");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nueva Contraseña");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Confirmar Contraseña");

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cedula");

        Imagen.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        SelImagen.setText("Seleccionar Imagen");
        SelImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_mensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_contraseña, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_verContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SelImagen)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_verContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SelImagen))
                .addGap(115, 115, 115)
                .addComponent(btn_registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_mensajes, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
//        LecturaE();
//        LecturaP();
//        LecturaA();
//        if (!txt_usuario.getText().isEmpty() && !txt_contraseña.getText().isEmpty() && !txt_verContraseña.getText().isEmpty() && !txt_cedula.getText().isEmpty() && !URL.isEmpty()) {
//            if (txt_contraseña.getText().equals(txt_verContraseña.getText())) {
//                if (rdb_estudiante.isSelected()) {
//                    int i = 0;
//                    
//                    // comienza buscador estudiantes
//                    if (!launiversidad.estudiantes.isEmpty()){
//                        while(launiversidad.estudiantes.size()>i && txt_usuario.getText().equals(launiversidad.estudiantes.get(i).nombre)){
//                            i++;
//                        } 
//                        // termina buscador estudiantes
//
//                        if (i>launiversidad.estudiantes.size()) {
//                            JOptionPane.showMessageDialog(null, "Registro Fallido, Usuario Registrado","Error",JOptionPane.ERROR_MESSAGE);
//                        }else{
//                            Estudiante nuevoE = new Estudiante(txt_usuario.getText(),txt_contraseña.getText(),txt_cedula.getText(),URL);
//                            nuevoE.Guardar();
//                            launiversidad.estudiantes.add(nuevoE);
//                            JOptionPane.showMessageDialog(null, "Registro Exitoso","Informacion",JOptionPane.INFORMATION_MESSAGE);
//                            this.dispose();
//                        }
//                    }else{
//                       
//                            Estudiante nuevoE = new Estudiante(txt_usuario.getText(),txt_contraseña.getText(),txt_cedula.getText(),URL);
//                            launiversidad.estudiantes.add(nuevoE);
//                            nuevoE.Guardar();
//                            JOptionPane.showMessageDialog(null, "Registro Exitoso","Informacion",JOptionPane.INFORMATION_MESSAGE);
//                            this.dispose();
//                    }
//                            
//                }else{
//                    if (rdb_profesor.isSelected()) {
//                        //busca en profesores
//                         int i = 0;
//                         if (!launiversidad.profesores.isEmpty()){
//                            while(launiversidad.profesores.size()>i && txt_usuario.getText().equals(launiversidad.profesores.get(i).nombre)){
//                                i++;
//                            }
//                            if (i>launiversidad.profesores.size()) {
//                                JOptionPane.showMessageDialog(null, "Registro Fallido, Usuario Registrado","Error",JOptionPane.ERROR_MESSAGE);
//                            }else{
//                                Profesor nuevoP = new Profesor(txt_usuario.getText(),txt_contraseña.getText(),txt_cedula.getText(),URL);
//                                launiversidad.profesores.add(nuevoP);
//                                nuevoP.Guardar();
//                                JOptionPane.showMessageDialog(null, "Registro Exitoso","Informacion",JOptionPane.INFORMATION_MESSAGE);
//                                this.dispose();
//                            }
//                         }
//                         else{
//                             Profesor nuevoP = new Profesor(txt_usuario.getText(),txt_contraseña.getText(),txt_cedula.getText(),URL);
//                                launiversidad.profesores.add(nuevoP);
//                                nuevoP.Guardar();
//                                JOptionPane.showMessageDialog(null, "Registro Exitoso","Informacion",JOptionPane.INFORMATION_MESSAGE);
//                                this.dispose();
//                         }
//                    }else{
//                        //solo puede ser administrador
//                         int i = 0;
//                         if (!launiversidad.administradores.isEmpty()){
//                            while(launiversidad.administradores.size()>i && txt_usuario.getText().equals(launiversidad.administradores.get(i).nombre)){
//                                i++;
//                            }
//                            if (i>launiversidad.administradores.size()) {
//                                JOptionPane.showMessageDialog(null, "Registro Fallido, Usuario Registrado","Error",JOptionPane.ERROR_MESSAGE);
//                            }else{
//                                Administrador nuevo = new Administrador(txt_usuario.getText(),txt_contraseña.getText(),txt_cedula.getText(),URL);
//                                launiversidad.administradores.add(nuevo);
//                                JOptionPane.showMessageDialog(rootPane, URL);
//                               JOptionPane.showMessageDialog(null, "Registro Exitoso","Informacion",JOptionPane.INFORMATION_MESSAGE);
//                                nuevo.Guardar();
//                                this.dispose();
//
//                            }
//                         }else{
//                             Administrador nuevo = new Administrador(txt_usuario.getText(),txt_contraseña.getText(),txt_cedula.getText(),URL);
//                                launiversidad.administradores.add(nuevo);
//                                nuevo.Guardar();
//                                JOptionPane.showMessageDialog(null, "Registro Exitoso","Informacion",JOptionPane.INFORMATION_MESSAGE);
//                                this.dispose();
//
//                         }
//
//                    
//                    
//                    }
//                   
//                }
//            }else{
//                lbl_mensajes.setText("la contraseña no concuerda con la verificacion");
//            }
//        }else{
//            //faltan campos por llenar
//            lbl_mensajes.setText("Debe llenar todo el formulario");
//        }
//        this.dispose();

    }//GEN-LAST:event_btn_registrarActionPerformed
    public void LecturaE(){
            corredores.clear();
            String ruta = "Corredores";
            String nombr = "Corredores.txt";
            File archivo = new File(ruta,nombr);
            try(Scanner s = new Scanner(archivo)){
                while(s.hasNextLine()){
                        String Linea = s.nextLine();
                        String[] datos = Linea.split("//");
                        int Numero = Integer.parseInt(datos[0]);
                        int Edad = Integer.parseInt(datos[4]);
                        Corredor elE = new Corredor(Numero,datos[1],datos[2],datos[3],Edad,null);
                        corredores.add(elE);


                    }
            } catch (FileNotFoundException ex) {
                     System.out.println("test");
                    JOptionPane.showMessageDialog(null, "No se encontro el archivo");
            }

        }
    
    protected ImageIcon createImageIcon(String path) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_formWindowOpened
    
    private static void copyFileUsingJava7Files(File source, File dest)
            throws IOException {
        Files.copy(source.toPath(), dest.toPath());
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void SelImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelImagenActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF Images", "jpg", "gif","jfjf");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            //corredores.get(indice).Foto = chooser.getSelectedFile().getParent();
            
            String aux = chooser.getSelectedFile().getPath();
            String substring = aux.substring(aux.lastIndexOf("Lab2Estructuradedatos")+22);
            
            JOptionPane.showMessageDialog(rootPane, substring);
            
//            String Directorio = "ImagenUsuarios";
//            File f = new File(Directorio);
//            if(!f.exists()){
//                f.mkdirs();
//            }
//            System.out.println("You chose to open this file: " +
//                    chooser.getSelectedFile().getName());
//            File source = new File(chooser.getSelectedFile().getParent(),chooser.getSelectedFile().getName());
//            File dest = new File("ImagenUsuarios",txt_usuario.getText()+".jpg");
//            if(!txt_usuario.getText().equals("")){
//                try {
//                    copyFileUsingJava7Files(source, dest);
//                    URL = dest.toString();
//                    JOptionPane.showMessageDialog(rootPane, URL);
//                    ImageIcon imageIcon = new ImageIcon(new ImageIcon(URL).getImage().getScaledInstance(Imagen.getWidth(),Imagen.getHeight(), Image.SCALE_DEFAULT));
//                    Imagen.setIcon(imageIcon);
//                } catch (IOException ex) {
//                    Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
//                }
            }
         
        
        
        
    }//GEN-LAST:event_SelImagenActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton SelImagen;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_mensajes;
    private javax.swing.ButtonGroup rdbg_tipoEstudiante;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JTextField txt_verContraseña;
    // End of variables declaration//GEN-END:variables
}
